name: "test"

on: [push]

jobs:
  code:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os}}"

    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.9"
      fail-fast: false

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: pip install -r requirements_tests.txt

      - name: Test with pytest
        run: pytest --junitxml=junit/test-results-${{ matrix.os }}-${{ matrix.python-version }}.xml --cov-report xml:coverage/coverage-results-${{ matrix.os }}-${{ matrix.python-version }}.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          junit_files: "junit/test-results-*.xml"
          check_name: "Test Results for Python ${{ matrix.python-version }} on ${{ matrix.os }}"
        if: ${{ always() }}

      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-results-${{ matrix.os }}-${{ matrix.python-version }}
          path: coverage/coverage-results-${{ matrix.os }}-${{ matrix.python-version }}.xml
        if: ${{ always() }}

      - name: Upload Linux coverage to Codecov
        if: ${{ startsWith(runner.os, 'Linux') }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/coverage-results-${{ matrix.os }}-${{ matrix.python-version }}.xml